### ISSUE TITLE
[BUG] RuntimeError: Failed to import transformers.models.fuyu.processing_fuyu

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#111]
Traceback (most recent call last):
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/v/.local/lib/python3.10/site-packages/transformers/models/fuyu/processing_fuyu.py", line 29, in <module>
    from .image_processing_fuyu import FuyuBatchFeature
  File "/home/v/.local/lib/python3.10/site-packages/transformers/models/fuyu/image_processing_fuyu.py", line 180, in <module>
    class FuyuImageProcessor(BaseImageProcessor):
  File "/home/v/.local/lib/python3.10/site-packages/transformers/models/fuyu/image_processing_fuyu.py", line 365, in FuyuImageProcessor
    resample: Optional[PILImageResampling] = None,
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 403, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/lib/python3.10/typing.py", line 529, in Optional
    arg = _type_check(parameters, f"{self} requires a single type.")
  File "/usr/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: typing.Optional requires a single type. Got <module 'PIL.Image' from '/usr/lib/python3/dist-packages/PIL/Image.py'>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/v/swarms/fuyu.py", line 1, in <module>
    from swarms.models.fuyu import Fuyu
  File "/home/v/swarms/swarms/models/fuyu.py", line 2, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1336, in __getattr__
    value = getattr(module, name)
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.fuyu.processing_fuyu because of the following error (look up to see its traceback):
typing.Optional requires a single type. Got <module 'PIL.Image' from '/usr/lib/python3/dist-packages/PIL/Image.py'>.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/111">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/111/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/111/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 I still don't know what this error is,

**Comment by kyegomez** [comment]
@vyomakesh09 try again
