### ISSUE TITLE
[BUG] example.py marshmallow not found

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#127]
**Describe the bug**
clean install
ran example.com
```
Traceback (most recent call last):
  File "/content/swarms/example.py", line 1, in <module>
    from swarms.models import OpenAIChat
  File "/content/swarms/swarms/__init__.py", line 10, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/content/swarms/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.swarms.autoscaler import AutoScaler
  File "/content/swarms/swarms/swarms/autoscaler.py", line 5, in <module>
    from swarms.structs.flow import Flow
  File "/content/swarms/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.workflow import Workflow
  File "/content/swarms/swarms/structs/workflow.py", line 6, in <module>
    from swarms.structs.task import Task
  File "/content/swarms/swarms/structs/task.py", line 12, in <module>
    from swarms.artifacts.error_artifact import ErrorArtifact
  File "/content/swarms/swarms/artifacts/error_artifact.py", line 3, in <module>
    from swarms.artifacts.base import BaseArtifact
  File "/content/swarms/swarms/artifacts/base.py", line 6, in <module>
    from marshmallow import class_registry
ModuleNotFoundError: No module named 'marshmallow'
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/127">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/127/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/127/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Likely fix, adding marshmallow to dependencies pyproject.toml, and swarms/swarms/artifacts __init__.py

**Comment by evelynmitchell** [comment]
After adding pip install marshmallow, the error changes to:
```
Installing collected packages: marshmallow
Successfully installed marshmallow-3.20.1
Traceback (most recent call last):
  File "/content/swarms/example.py", line 1, in <module>
    from swarms.models import OpenAIChat
  File "/content/swarms/swarms/__init__.py", line 10, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/content/swarms/swarms/swarms/__init__.py", line 3, in <module>
    from swarms.swarms.orchestrate import Orchestrator
  File "/content/swarms/swarms/swarms/orchestrate.py", line 8, in <module>
    import chromadb
ModuleNotFoundError: No module named 'chromadb'
```

**Comment by evelynmitchell** [comment]
I was testing with this notebook, doing a poetry install. 
Had to add 'pip install chromadb'
example.py produces no output, but it runs.

```
!git clone https://github.com/kyegomez/swarms
%cd /content/swarms
!pip install poetry
!poetry install

!pip install marshmallow
!pip install chromadb

import os
os.environ['OPENAI_API_KEY'] = "  "

!python3 example.py
```

**Comment by kyegomez** [comment]
@evelynmitchell thanks for reporting these issues, I've fixed the marshmellow and chromadb by adding it into requirements and pyproejct.toml and the example.py does not run because OPENAI changed their api, so it will not work unless we update the api, until then try a different model!
