### ISSUE TITLE
[BUG] RuntimeError: no validator found for <class 'transformers.models.auto.modeling_auto.AutoModelForVision2Seq'>, see `arbitrary_types_allowed` in Config

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#140]
Traceback (most recent call last):
  File "/home/v/swarms/tests/models/kosmos2.py", line 4, in <module>
    from swarms.models.kosmos2 import Kosmos2, Detections
  File "/home/v/.local/lib/python3.10/site-packages/swarms/models/kosmos2.py", line 34, in <module>
    class Kosmos2(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'transformers.models.auto.modeling_auto.AutoModelForVision2Seq'>, see `arbitrary_types_allowed` in Config

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/140">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/140/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/140/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This can be closed.
