### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#142]
```
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/tests/swarms/autoscaler.py
Traceback (most recent call last):
  File "/home/v/swarms/tests/swarms/autoscaler.py", line 2, in <module>
    from swarms.swarms.autoscaler import AutoScaler, Worker
  File "/home/v/swarms/tests/swarms/swarms.py", line 4, in <module>
    from swarms.swarms.swarms import (
ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/tests/swarms/autoscaler.py
Traceback (most recent call last):
  File "/home/v/swarms/tests/swarms/autoscaler.py", line 2, in <module>
    from swarms.autoscaler import AutoScaler, Worker
  File "/home/v/swarms/tests/swarms/swarms.py", line 4, in <module>
    from swarms.swarms.swarms import (
ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/tests/swarms/dialogue_simulator.py
Traceback (most recent call last):
  File "/home/v/swarms/tests/swarms/dialogue_simulator.py", line 2, in <module>
    from swarms.swarms.dialogue_simulator import DialogueSimulator, Worker
  File "/home/v/swarms/tests/swarms/swarms.py", line 4, in <module>
    from swarms.swarms.swarms import (
ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/tests/swarms/godmode.py
Traceback (most recent call last):
  File "/home/v/swarms/tests/swarms/godmode.py", line 2, in <module>
    from swarms.swarms.god_mode import GodMode, LLM
  File "/home/v/swarms/tests/swarms/swarms.py", line 4, in <module>
    from swarms.swarms.swarms import (
ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/tests/swarms/groupchat.py
Traceback (most recent call last):
  File "/home/v/swarms/tests/swarms/groupchat.py", line 3, in <module>
    from swarms.models import OpenAIChat
  File "/home/v/swarms/tests/swarms/swarms.py", line 4, in <module>
    from swarms.swarms.swarms import (
ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/tests/swarms/multi_agent_collab.py
Traceback (most recent call last):
  File "/home/v/swarms/tests/swarms/multi_agent_collab.py", line 2, in <module>
    from swarms.swarms.multi_agent_collab import (
  File "/home/v/swarms/tests/swarms/swarms.py", line 4, in <module>
    from swarms.swarms.swarms import (
ModuleNotFoundError: No module named 'swarms.swarms'; 'swarms' is not a package``
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/142">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/142/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/142/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 this has been fixed, run the tests again
