### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'swarms.utils.display_markdown'

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#174]
Traceback (most recent call last):
  File "c:\Users\Guest1\Desktop\pliny-swarms\example.py", line 1, in <module>
    from swarms.models import OpenAIChat
  File "c:\Users\Guest1\Desktop\pliny-swarms\swarms\__init__.py", line 18, in <module>
    from swarms.swarms import *  # noqa: E402, F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guest1\Desktop\pliny-swarms\swarms\swarms\__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "c:\Users\Guest1\Desktop\pliny-swarms\swarms\structs\__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "c:\Users\Guest1\Desktop\pliny-swarms\swarms\structs\flow.py", line 12, in <module>
    from swarms.utils.code_interpreter import SubprocessCodeInterpreter
  File "c:\Users\Guest1\Desktop\pliny-swarms\swarms\utils\__init__.py", line 1, in <module>
    from swarms.utils.display_markdown import display_markdown_message
ModuleNotFoundError: No module named 'swarms.utils.display_markdown'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/174">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/174/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/174/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius I just pushed to try and fix this lmk if it works
