### ISSUE TITLE
[BUG] pydantic root_validator deprecated - blocks test running

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#195]
**Describe the bug**
Running example.py or multi_modal_auto_agent.py  or sequential_workflow_example.py within the top level docker container.

```
root@d789676bb63b:/usr/src/swarm_cloud# python example.py 
Traceback (most recent call last):
  File "/usr/src/swarm_cloud/example.py", line 6, in <module>
    from swarms.models import OpenAIChat
  File "/usr/src/swarm_cloud/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/usr/src/swarm_cloud/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/usr/src/swarm_cloud/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/usr/src/swarm_cloud/swarms/structs/flow.py", line 14, in <module>
    from swarms.tools.tool import BaseTool
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 271, in BaseTool
    @root_validator()
  File "/usr/local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
root@d789676bb63b:/usr/src/swarm_cloud# ls *.py
example.py  multi_modal_auto_agent.py  sequential_workflow_example.py
root@d789676bb63b:/usr/src/swarm_cloud# python multi_modal_auto_agent.py 
Traceback (most recent call last):
  File "/usr/src/swarm_cloud/multi_modal_auto_agent.py", line 1, in <module>
    from swarms.structs import Flow
  File "/usr/src/swarm_cloud/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/usr/src/swarm_cloud/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/usr/src/swarm_cloud/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/usr/src/swarm_cloud/swarms/structs/flow.py", line 14, in <module>
    from swarms.tools.tool import BaseTool
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 271, in BaseTool
    @root_validator()
  File "/usr/local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
root@d789676bb63b:/usr/src/swarm_cloud# python sequential_workflow_example.py 
Traceback (most recent call last):
  File "/usr/src/swarm_cloud/sequential_workflow_example.py", line 1, in <module>
    from swarms.models import OpenAIChat, BioGPT, Anthropic
  File "/usr/src/swarm_cloud/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/usr/src/swarm_cloud/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/usr/src/swarm_cloud/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/usr/src/swarm_cloud/swarms/structs/flow.py", line 14, in <module>
    from swarms.tools.tool import BaseTool
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 271, in BaseTool
    @root_validator()
  File "/usr/local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
root@d789676bb63b:/usr/src/swaTraceback (most recent call last):
  File "/usr/src/swarm_cloud/sequential_workflow_example.py", line 1, in <module>
    from swarms.models import OpenAIChat, BioGPT, Anthropic
  File "/usr/src/swarm_cloud/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/usr/src/swarm_cloud/swarms/swarms/__init__.py", line 2, in <module>


    from swarms.structs.autoscaler import AutoScaler
  File "/usr/src/swarm_cloud/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/usr/src/swarm_cloud/swarms/structs/flow.py", line 14, in <module>
    from swarms.tools.tool import BaseTool
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 271, in BaseTool
    @root_validator()
  File "/usr/local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
root@d789676bb63b:/usr/src/swarm_cloud# ```

** See
(https://docs.pydantic.dev/latest/migration/#validator-and-root_validator-are-deprecated) as a pointer to a fix for tool.py line 271

<!-- POLAR PLEDGE BADGE START -->
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/195">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/195/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/195/pledge.svg">
</picture>
</a>
<!-- POLAR PLEDGE BADGE END -->

**Comment by evelynmitchell** [comment]
I've installed bump_pydantic and run it on my local copy, following the instructions here: (https://docs.pydantic.dev/2.5/migration/) 

It touched 16 files, in what appear to be very reasonable ways. I'm not going to commit this as the tail end of the cicd PR.

**Comment by evelynmitchell** [comment]
I think this can be closed
