### ISSUE TITLE
[BUG] Ssd (stable diffusion) error

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#199]
Loading pipeline components...:   0%|                                                                                            | 0/7 [00:00<?, ?it/s]
Loading pipeline components...:  14%|############                                                                        | 1/7 [00:00<00:00,  8.16it/s]
Loading pipeline components...:  29%|########################                                                            | 2/7 [00:00<00:00,  8.21it/s]
Loading pipeline components...:  43%|####################################                                                | 3/7 [00:00<00:00,  4.57it/s]
Loading pipeline components...:  71%|############################################################                        | 5/7 [00:00<00:00,  5.94it/s]
Loading pipeline components...: 100%|####################################################################################| 7/7 [00:01<00:00,  5.95it/s]
Loading pipeline components...: 100%|####################################################################################| 7/7 [00:01<00:00,  5.96it/s]
Traceback (most recent call last):
  File "c:\Users\Guest1\Desktop\p-swarms\stable.py", line 1, in <module>
    from swarms.models.ssd_1b import SSD1B
  File "c:\Users\Guest1\Desktop\p-swarms\swarms\models\ssd_1b.py", line 18, in <module>
    class SSD1B:
  File "c:\Users\Guest1\Desktop\p-swarms\swarms\models\ssd_1b.py", line 60, in SSD1B
    ).to(device)
      ^^^^^^^^^^
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 852, in to
    module.to(device, dtype)
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/199">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/199/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/199/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius update your torch
