### ISSUE TITLE
[BUG] pydantic.errors.PydanticUserError:

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#206]
v@v-System-Product-Name:~/swarms$ /bin/python3 /home/v/swarms/sequential_workflow_example.py
Traceback (most recent call last):
  File "/home/v/swarms/sequential_workflow_example.py", line 1, in <module>
    from swarms.models import OpenAIChat, BioGPT, Anthropic
  File "/home/v/swarms/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/home/v/swarms/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/home/v/swarms/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/home/v/swarms/swarms/structs/flow.py", line 12, in <module>
    from swarms.tools.tool import BaseTool
  File "/home/v/swarms/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/home/v/swarms/swarms/tools/tool.py", line 271, in BaseTool
    @root_validator()
  File "/home/v/.local/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/206">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/206/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/206/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Checked out an up to date version of the repo, built a container from the Dockerfile.
```
root@485bab1a3ef0:/usr/src/swarm_cloud#  python example.py 
Traceback (most recent call last):
  File "/usr/src/swarm_cloud/example.py", line 6, in <module>
    from swarms.models import OpenAIChat
  File "/usr/src/swarm_cloud/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/usr/src/swarm_cloud/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/usr/src/swarm_cloud/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/usr/src/swarm_cloud/swarms/structs/flow.py", line 12, in <module>
    from swarms.tools.tool import BaseTool
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 271, in BaseTool
    @root_validator()
  File "/usr/local/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
root@485bab1a3ef0:/usr/src/swarm_cloud# pip install bump-pydantic
Collecting bump-pydantic
  Downloading bump_pydantic-0.7.0-py3-none-any.whl.metadata (10 kB)
Collecting libcst (from bump-pydantic)
  Downloading libcst-1.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (17 kB)
Requirement already satisfied: rich in /usr/local/lib/python3.9/site-packages (from bump-pydantic) (13.7.0)
Requirement already satisfied: typer>=0.7.0 in /usr/local/lib/python3.9/site-packages (from bump-pydantic) (0.9.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/site-packages (from bump-pydantic) (4.8.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.9/site-packages (from typer>=0.7.0->bump-pydantic) (8.1.7)
Requirement already satisfied: typing-inspect>=0.4.0 in /usr/local/lib/python3.9/site-packages (from libcst->bump-pydantic) (0.9.0)
Requirement already satisfied: pyyaml>=5.2 in /usr/local/lib/python3.9/site-packages (from libcst->bump-pydantic) (6.0.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.9/site-packages (from rich->bump-pydantic) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.9/site-packages (from rich->bump-pydantic) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.9/site-packages (from markdown-it-py>=2.2.0->rich->bump-pydantic) (0.1.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.9/site-packages (from typing-inspect>=0.4.0->libcst->bump-pydantic) (1.0.0)
Downloading bump_pydantic-0.7.0-py3-none-any.whl (28 kB)
Downloading libcst-1.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 18.8 MB/s eta 0:00:00
Installing collected packages: libcst, bump-pydantic
Successfully installed bump-pydantic-0.7.0 libcst-1.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@485bab1a3ef0:/usr/src/swarm_cloud# bump-pydantic .
[20:26:34] Start bump-pydantic.                                       main.py:61
           Found 268 files to process                                 main.py:76
[20:28:10] Refactored 15 files.                                      main.py:141
           Run successfully!                                         main.py:149
root@485bab1a3ef0:/usr/src/swarm_cloud# python example.py 
Traceback (most recent call last):
  File "/usr/src/swarm_cloud/example.py", line 6, in <module>
    from swarms.models import OpenAIChat
  File "/usr/src/swarm_cloud/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/usr/src/swarm_cloud/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/usr/src/swarm_cloud/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.flow import Flow
  File "/usr/src/swarm_cloud/swarms/structs/flow.py", line 12, in <module>
    from swarms.tools.tool import BaseTool
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 119, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/usr/src/swarm_cloud/swarms/tools/tool.py", line 272, in BaseTool
    @model_validator()
TypeError: model_validator() missing 1 required keyword-only argument: 'mode'
root@485bab1a3ef0:/usr/src/swarm_cloud# 

```

**Comment by evelynmitchell** [comment]
This can be closed.
