### ISSUE TITLE
[BUG] I get an error when trying to install with pip install on windows 11

### ISSUE THREAD

**Issue by Mako-L** [kyegomez/swarms#21]
**Describe the bug**

**To Reproduce**
1. Go to cmd
2. Run 'pip install swarms'
3. I get Errors

**Expected behavior**

**Screenshots**

**Additional context**

```python
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Building wheels for collected packages: google-search-results, Pillow, sentencepiece, wget, wikipedia, fast-bss-eval, basicsr, bs4, ggl, antlr4-python3-runtime, test-tube, ctc-segmentation, scikit-image, stringcase, torch-stoi, validators, ci-sdr, ffmpy, future, julius, audioread, jaconv, mir-eval, pesq, pystoi, distance
  Building wheel for google-search-results (pyproject.toml) ... done
  Created wheel for google-search-results: filename=google_search_results-2.4.2-py3-none-any.whl size=32076 sha256=e6c51d57bc6c6119f5dd8396417a0b1826525e47d61692867e1793b728c48cba
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\6e\42\3e\aeb691b02cb7175ec70e2da04b5658d4739d2b41e5f73cd06f
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [199 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
    
      [...]

      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "<string>", line 989, in <module>
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 804, in build_extensions
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\Mako\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Mako\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Mako\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Mako\AppData\Local\Temp\pip-build-env-1rb622qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1009, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      <string>:45: RuntimeWarning: Pillow 9.0.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Building wheel for sentencepiece (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for sentencepiece (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/__init__.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/_version.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece
      running build_ext
      building 'sentencepiece._sentencepiece' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\sentencepiece
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpsrc/sentencepiece/sentencepiece_wrap.cxx /Fobuild\temp.win-amd64-cpython-311\Release\src/sentencepiece/sentencepiece_wrap.obj /std:c++17 /MT /I..\build\root\include
      cl : Command line warning D9025 : overriding '/MD' with '/MT'
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2822): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
  Building wheel for wget (pyproject.toml) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9681 sha256=1282f62a07aa70236894f95ef5169b9b7d3937f111304afd7feabc5967b96fc2
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\40\b3\0f\a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
  Building wheel for wikipedia (pyproject.toml) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11706 sha256=578792ce700a33b6045021f419231862107683a1ba0338e9d550a143785af6b4
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\8f\ab\cb\45ccc40522d3a1c41e1d2ad53b8f33a62f394011ec38cd71c6
  Building wheel for fast-bss-eval (pyproject.toml) ... done
  Created wheel for fast-bss-eval: filename=fast_bss_eval-0.1.3-py3-none-any.whl size=44282 sha256=ba76c586c8c534b8742b36188520e1ba2c0aacee02d9208eac967f3daef419eb
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\2f\d5\72\11a8ce448bcaf14da47a215ac5131bb3aaea2cb4dc2a749db6
  Building wheel for basicsr (pyproject.toml) ... done
  Created wheel for basicsr: filename=basicsr-1.4.2-py3-none-any.whl size=214848 sha256=e362594bd5f70798f317958fe1ad1ec5a3245b4ee7273a6eb5c867bec4e42f08
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\6d\a4\b3\9f888ba88efcae6dd4bbce69832363de9c4051142674f779fa
  Building wheel for bs4 (pyproject.toml) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1266 sha256=9e31c84f7920295942ae804f78ddd14b28afd08ea743a90188031dee150a3143
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\d4\c8\5b\b5be9c20e5e4503d04a6eac8a3cd5c2393505c29f02bea0960
  Building wheel for ggl (pyproject.toml) ... done
  Created wheel for ggl: filename=ggl-1.1.0-py3-none-any.whl size=1971 sha256=bf75d8994c51ec80086561c9bdbac098ea54039c97cf936e73836d1f16ce291e
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\2b\99\16\6cc4997f1c55ca12c32d5011bc97d9fa40b31a75c065d5ce78
  Building wheel for antlr4-python3-runtime (pyproject.toml) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144578 sha256=b4817ef37a46e9c8bac1d064606db70a0b7e89065396870e51762d645d992336
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\1a\97\32\461f837398029ad76911109f07047fde1d7b661a147c7c56d1
  Building wheel for test-tube (pyproject.toml) ... done
  Created wheel for test-tube: filename=test_tube-0.7.5-py3-none-any.whl size=25340 sha256=3c07c7862c2617c98b5f10f392df73e02370ee648919a70fb62c786147d643a0
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\bd\ba\61\6afbaf4b593765f126f73e502b6d48a8c85fbcbd582f62ea47
  Building wheel for ctc-segmentation (pyproject.toml) ... done
  Created wheel for ctc-segmentation: filename=ctc_segmentation-1.7.4-cp311-cp311-win_amd64.whl size=45121 sha256=75ec28e652a64c6af5897a555cad376b583f12cc6863fbae74071ac33fa95e8a
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\b2\39\af\4cbf13dcd38573884e16d39aaa330b5627d7552245c76cc922
  Building wheel for scikit-image (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for scikit-image (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [759 lines of output]
      setup.py:9: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        from numpy.distutils.command.build_ext import build_ext as npy_build_ext
      Partial import of skimage during the build process.
      Compiling C:\Users\Mako\AppData\Local\Temp\pip-install-bmf5h7s1\scikit-image_5e6fafb0fa8941c299aef0f8629d90a5\skimage\morphology\_skeletonize_3d_cy.pyx because it changed.
      [1/1] Cythonizing C:\Users\Mako\AppData\Local\Temp\pip-install-bmf5h7s1\scikit-image_5e6fafb0fa8941c299aef0f8629d90a5\skimage\morphology\_skeletonize_3d_cy.pyx
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "skimage._shared.geometry" sources
      INFO: building extension "skimage._shared.transform" sources
      INFO: building extension "skimage._shared.interpolation" sources
      INFO: building extension "skimage._shared.fast_exp" sources
      INFO: building extension "skimage.draw._draw" sources
      INFO: building extension "skimage.feature._cascade" sources
      INFO: building extension "skimage.feature.corner_cy" sources
      INFO: building extension "skimage.feature.censure_cy" sources
      INFO: building extension "skimage.feature.orb_cy" sources
      INFO: building extension "skimage.feature._texture" sources
      INFO: building extension "skimage.feature._hoghistogram" sources
      INFO: building extension "skimage.feature._haar" sources
      INFO: building extension "skimage.feature._sift" sources
      INFO: building extension "skimage.feature.brief_cy" sources
      INFO: building extension "skimage.feature._hessian_det_appx" sources
      INFO: building extension "skimage.restoration._unwrap_1d" sources
      INFO: building extension "skimage.restoration._unwrap_2d" sources
      INFO: building extension "skimage.restoration._unwrap_3d" sources
      INFO: building extension "skimage.restoration._denoise_cy" sources
      INFO: building extension "skimage.restoration._nl_means_denoising" sources
      INFO: building extension "skimage.restoration._rolling_ball_cy" sources
      INFO: building extension "skimage.restoration._inpaint" sources
      INFO: building extension "skimage.filters.rank.core_cy" sources
      INFO: building extension "skimage.filters.rank.core_cy_3d" sources
      INFO: building extension "skimage.filters._multiotsu" sources
      INFO: building extension "skimage.filters.rank.generic_cy" sources
      INFO: building extension "skimage.filters.rank.percentile_cy" sources
      INFO: building extension "skimage.filters.rank.bilateral_cy" sources
      INFO: building extension "skimage.future.graph._ncut_cy" sources
      INFO: building extension "skimage.graph._spath" sources
      INFO: building extension "skimage.graph._mcp" sources
      INFO: building extension "skimage.graph.heap" sources
      INFO: building extension "skimage.io._plugins._colormixer" sources
      INFO: building extension "skimage.io._plugins._histograms" sources
      INFO: building extension "skimage.measure._ccomp" sources
      INFO: building extension "skimage.measure._find_contours_cy" sources
      INFO: building extension "skimage.measure._moments_cy" sources
      INFO: building extension "skimage.measure._marching_cubes_classic_cy" sources
      INFO: building extension "skimage.measure._marching_cubes_lewiner_cy" sources
      INFO: building extension "skimage.measure._pnpoly" sources
      INFO: building extension "skimage.morphology._skeletonize_cy" sources
      INFO: building extension "skimage.morphology._convex_hull" sources
      INFO: building extension "skimage.morphology._grayreconstruct" sources
      INFO: building extension "skimage.morphology._max_tree" sources
      INFO: building extension "skimage.morphology._skeletonize_3d_cy" sources
      INFO: building extension "skimage.morphology._extrema_cy" sources
      INFO: building extension "skimage.morphology._flood_fill_cy" sources
      INFO: building extension "skimage.transform._hough_transform" sources
      INFO: building extension "skimage.transform._warps_cy" sources
      INFO: building extension "skimage.transform._radon_transform" sources
      INFO: building extension "skimage.util._remap" sources
      INFO: building extension "skimage.segmentation._watershed_cy" sources
      INFO: building extension "skimage.segmentation._felzenszwalb_cy" sources
      INFO: building extension "skimage.segmentation._quickshift_cy" sources
      INFO: building extension "skimage.segmentation._slic" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      running build_py
  
[...]



      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using ConditionalOpenMP
      INFO: CCompilerOpt.cc_test_flags[1085] : testing flags (/O2)
      creating C:\Users\Mako\AppData\Local\Temp\tmpdorups9n\Users
      creating C:\Users\Mako\AppData\Local\Temp\tmpdorups9n\Users\Mako
      creating C:\Users\Mako\AppData\Local\Temp\tmpdorups9n\Users\Mako\AppData

    [...]

      INFO: CCompilerOpt._parse_target_tokens[2032] : skip targets (FMA4 VX VSX VXE2 VXE ASIMD NEON XOP VSX2 VSX4 VSX3) not part of baseline or dispatch-able features
      INFO: CCompilerOpt._parse_policy_not_keepbase[2144] : skip baseline features (SSE2)
      INFO: CCompilerOpt.generate_dispatch_header[2365] : generate CPU dispatch header: (build\src.win-amd64-3.11\numpy\distutils\include\npy_cpu_dispatch_config.h)
      WARN: CCompilerOpt.generate_dispatch_header[2374] : dispatch header dir build\src.win-amd64-3.11\numpy\distutils\include does not exist, creating it
      INFO: CCompilerOpt.feature_extra_checks[1639] : Testing extra checks for feature 'AVX512F' (AVX512F_REDUCE)
      INFO: CCompilerOpt.feature_extra_checks[1639] : Testing extra checks for feature 'AVX512_SKX' (AVX512BW_MASK AVX512DQ_MASK)
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      WARN: Missing compiler_cxx fix for MSVCCompiler
      INFO: customize MSVCCompiler using ConditionalOpenMP
      INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tctest.c /Fotest.obj /openmp
    
    [...]
    
      INFO: building 'skimage.feature.brief_cy' extension
      INFO: compiling C sources
      INFO: clang-cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -IC:\Users\Mako\AppData\Local\Temp\pip-build-env-8_k1rim6\overlay\Lib\site-packages/pythran -IC:\Users\Mako\AppData\Local\Temp\pip-build-env-8_k1rim6\overlay\Lib\site-packages\numpy\core\include -IC:\Users\Mako\AppData\Local\Temp\pip-build-env-8_k1rim6\overlay\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpskimage/feature/brief_pythran.cpp /Fobuild\temp.win-amd64-3.11\Release\skimage/feature/brief_pythran.obj /std:c++14 /w /openmp /Zm1000


      [WinError 2] The system cannot find the file specified


      error: Command "clang-cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -IC:\Users\Mako\AppData\Local\Temp\pip-build-env-8_k1rim6\overlay\Lib\site-packages/pythran -IC:\Users\Mako\AppData\Local\Temp\pip-build-env-8_k1rim6\overlay\Lib\site-packages\numpy\core\include -IC:\Users\Mako\AppData\Local\Temp\pip-build-env-8_k1rim6\overlay\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Users\Mako\AppData\Local\Programs\Python\Python311\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpskimage/feature/brief_pythran.cpp /Fobuild\temp.win-amd64-3.11\Release\skimage/feature/brief_pythran.obj /std:c++14 /w /openmp /Zm1000" failed with exit status 127
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[863] : write cache to path -> C:\Users\Mako\AppData\Local\Temp\pip-install-bmf5h7s1\scikit-image_5e6fafb0fa8941c299aef0f8629d90a5\build\temp.win-amd64-3.11\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
  Building wheel for stringcase (pyproject.toml) ... done
  Created wheel for stringcase: filename=stringcase-1.2.0-py3-none-any.whl size=3581 sha256=0dce040fea2f17722f9e5faf995980432d6177c45d7f70d0290cb5a7e6db71f5
  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\b4\33\6d\d0820be98063da218c3206fbad2381cd2db3fbb1a0f0d254b5
 
[...]

  Stored in directory: c:\users\mako\appdata\local\pip\cache\wheels\fb\cd\9c\3ab5d666e3bcacc58900b10959edd3816cc9557c7337986322
Successfully built google-search-results wget wikipedia fast-bss-eval basicsr bs4 ggl antlr4-python3-runtime test-tube ctc-segmentation stringcase torch-stoi validators ci-sdr ffmpy future julius audioread jaconv mir-eval pesq pystoi distance
Failed to build Pillow sentencepiece scikit-image
ERROR: Could not build wheels for Pillow, sentencepiece, scikit-image, which is required to install pyproject.toml-based projects
```

**Comment by kyegomez** [comment]
@Mako-L Done!
