### ISSUE TITLE
[BUG] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by askvyas** [kyegomez/swarms#241]
Traceback (most recent call last):
  File "ex1.py", line 2, in <module>
    import swarms
  File "/home/vyas/swarms/swarm_env/lib/python3.8/site-packages/swarms/__init__.py", line 1, in <module>
    from swarms.utils.disable_logging import disable_logging
  File "/home/vyas/swarms/swarm_env/lib/python3.8/site-packages/swarms/utils/__init__.py", line 2, in <module>
    from swarms.utils.futures import execute_futures_dict
  File "/home/vyas/swarms/swarm_env/lib/python3.8/site-packages/swarms/utils/futures.py", line 7, in <module>
    def execute_futures_dict(fs_dict: dict[str, futures.Future[T]]) -> dict[str, T]:
TypeError: 'type' object is not subscriptable

Faced this issue while running the example agent on Ubuntu 20.4 OS

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/241">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/241/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/241/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@askvyas Thanks for the issue, I'm submitting an update now it works for me, try again please.

**Comment by askvyas** [comment]
upgraded using pip3 install --upgrade swarms 

still getting the same issue 
Traceback (most recent call last):
  File "ex1.py", line 2, in <module>
    import swarms
  File "/home/vyas/.local/lib/python3.8/site-packages/swarms/__init__.py", line 1, in <module>
    from swarms.utils.disable_logging import disable_logging
  File "/home/vyas/.local/lib/python3.8/site-packages/swarms/utils/__init__.py", line 2, in <module>
    from swarms.utils.futures import execute_futures_dict
  File "/home/vyas/.local/lib/python3.8/site-packages/swarms/utils/futures.py", line 7, in <module>
    def execute_futures_dict(fs_dict: dict[str, futures.Future[T]]) -> dict[str, T]:
TypeError: 'type' object is not subscriptable

**Comment by kyegomez** [comment]
@askvyas try `pip3 install --upgrade swarms==2.5.4`

**Comment by askvyas** [comment]
(swarm_env) vyas@askv:~/swarms$ pip3 install --upgrade swarms==2.5.4
ERROR: Ignored the following versions that require a different python version: 2.4.6 Requires-Python >=3.9.1,<4.0.0; 2.4.7 Requires-Python >=3.9.1,<4.0.0; 2.4.8 Requires-Python >=3.9.1,<4.0.0; 2.5.0 Requires-Python >=3.9.1,<4.0.0; 2.5.1 Requires-Python >=3.9.1,<4.0.0; 2.5.4 Requires-Python >=3.9.1,<4.0.0
ERROR: Could not find a version that satisfies the requirement swarms==2.5.4 (from versions: 0.0.1, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.9, 0.2.0, 0.2.2, 0.2.3, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.8, 1.1.9, 1.2.0, 1.2.1, 1.2.2, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.9, 1.3.0, 1.3.1, 1.3.2, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.9, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.6, 1.4.7, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.9, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.8.0, 1.8.1, 1.8.2, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 2.0.0, 2.0.1, 2.0.3, 2.0.4, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.9, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4)
ERROR: No matching distribution found for swarms==2.5.4

**Comment by kyegomez** [comment]
@askvyas then try `pip3 install --upgrade swarms`

**Comment by askvyas** [comment]
Sorry @vyomakesh09 @kyegomez, the python version I had was 3.8.x. Couldn't see anywhere on the readme that versions >=3.9.x are required. Updated python to 3.9
getting the following error now 
Traceback (most recent call last):
  File "/home/vyas/swarms/examples/ex1.py", line 6, in <module>
    from swarms.models import OpenAIChat
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/swarms/__init__.py", line 6, in <module>
    from swarms.swarms import *  # noqa: E402, F403
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/swarms/swarms/__init__.py", line 2, in <module>
    from swarms.structs.autoscaler import AutoScaler
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.agent import Agent
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/swarms/structs/agent.py", line 24, in <module>
    from swarms.tools.tool import BaseTool
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/swarms/tools/tool.py", line 120, in <module>
    class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/swarms/tools/tool.py", line 279, in BaseTool
    @root_validator()
  File "/home/vyas/.virtualenvs/swarm_env/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
