### ISSUE TITLE
[BUG] transformers issue

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#261]
In colab (https://colab.research.google.com/drive/1E-6y5_r4YgMhEbyGRlG4kWVtI2dKPrQi#scrollTo=bdc6De61nBMv)

```
DEBUG:root:Initializing MLIR with module: _site_initialize_0
Initializing MLIR with module: _site_initialize_0
DEBUG:root:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.10/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.10/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
etils.epath found. Using etils.epath for file I/O.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1353, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py", line 75, in <module>
    from .table_question_answering import TableQuestionAnsweringArgumentHandler, TableQuestionAnsweringPipeline
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/table_question_answering.py", line 26, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/substrates/__init__.py", line 17, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 138, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 57, in __dir__
    module = self._load()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 37, in _load
    self._on_first_access()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 59, in _validate_tf_environment
    raise ImportError(
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.14; Detected an installation of version 2.12.0. Please upgrade TensorFlow to proceed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/swarms/example.py", line 6, in <module>
    from swarms.models import OpenAIChat
  File "/content/swarms/swarms/__init__.py", line 8, in <module>
    from swarms.models import *  # noqa: E402, F403
  File "/content/swarms/swarms/models/__init__.py", line 11, in <module>
    from swarms.models.zephyr import Zephyr  # noqa: E402
  File "/content/swarms/swarms/models/zephyr.py", line 3, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1343, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1355, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
This version of TensorFlow Probability requires TensorFlow version >= 2.14; Detected an installation of version 2.12.0. Please upgrade TensorFlow to proceed.
```

**Comment by evelynmitchell** [comment]
Appears to be fixed by:
```
pip uninstall tensorflow
pip install tensorflow
```

**Comment by kyegomez** [comment]
@evelynmitchell fixed by adding tensorflow
