### ISSUE TITLE
[BUG] numba doesnt play nice with python 3.12

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#283]
Collecting requests<3,>=2 (from langchain==0.0.240->swarms)
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting typing-extensions>=4.2.0 (from pydantic->swarms)
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting uvicorn==0.18.3 (from uvicorn[standard]==0.18.3->pegasusx->swarms)
  Using cached uvicorn-0.18.3-py3-none-any.whl (57 kB)
Collecting pegasusx (from swarms)
  Using cached pegasusX-0.3.8-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.3.7-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.3.6-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.3.5-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.3.4-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.3.2-py3-none-any.whl.metadata (1.1 kB)
INFO: pip is still looking at multiple versions of pegasusx to determine which version is compatible with other requirements. This could take a while.
  Using cached pegasusX-0.3.1-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.3.0-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.2.9-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.2.7-py3-none-any.whl.metadata (1.1 kB)
  Using cached pegasusX-0.2.5-py3-none-any.whl.metadata (626 bytes)
Collecting numba (from pegasusx->swarms)
  Using cached numba-0.58.1.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fk/s283mdwd26z5zhm4gjlbbkk00000gn/T/pip-build-env-y_weiv9s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fk/s283mdwd26z5zhm4gjlbbkk00000gn/T/pip-build-env-y_weiv9s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fk/s283mdwd26z5zhm4gjlbbkk00000gn/T/pip-build-env-y_weiv9s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/fk/s283mdwd26z5zhm4gjlbbkk00000gn/T/pip-build-env-y_weiv9s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.12.1; only versions >=3.8,<3.12 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
nate@Nates-MacBook-Pro ~ % 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/283">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/283/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/283/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius pegasus was removed
