### ISSUE TITLE
[BUG] ImportError: cannot import name 'create_base_retry_decorator' from 'langchain.llms.base' 

### ISSUE THREAD

**Issue by peytontolbert** [kyegomez/swarms#368]
Traceback (most recent call last):
  File "D:\resumewebsite\functioncalling\swarms-master\vision.py", line 1, in <module>
    from swarms import QwenVLMultiModal
  File "D:\resumewebsite\functioncalling\swarms-master\swarms\__init__.py", line 6, in <module>
    from swarms.agents import *  # noqa: E402, F403
  File "D:\resumewebsite\functioncalling\swarms-master\swarms\agents\__init__.py", line 3, in <module>
    from swarms.agents.simple_agent import SimpleAgent
  File "D:\resumewebsite\functioncalling\swarms-master\swarms\agents\simple_agent.py", line 2, in <module>
    from swarms.models.base_llm import AbstractLLM
  File "D:\resumewebsite\functioncalling\swarms-master\swarms\models\__init__.py", line 6, in <module>
    from swarms.models.openai_models import (
  File "D:\resumewebsite\functioncalling\swarms-master\swarms\models\openai_models.py", line 26, in <module>
    from langchain.llms.base import BaseLLM, create_base_retry_decorator
ImportError: cannot import name 'create_base_retry_decorator' from 'langchain.llms.base' (C:\Users\Peyton\anaconda3\lib\site-packages\langchain\llms\base.py)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/368">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/368/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/368/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@peytontolbert try again when you have a chance by upgrading your swarms:

$ pip install -U swarms

**Comment by kyegomez** [comment]
@peytontolbert LMK if it's working pls
