### ISSUE TITLE
[BUG] TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by starshipvc** [kyegomez/swarms#399]
```
/Users/athena/Desktop/athena/sam_altman.py
/Users/athena/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
swarms is up to date!
Traceback (most recent call last):
    from swarms import Agent, ChromaDB, OpenAIChat
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/__init__.py", line 7, in <module>
    from swarms.agents import *  # noqa: E402, F403
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/agents/__init__.py", line 1, in <module>
    from swarms.agents.agent_wrapper import agent_wrapper
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/agents/agent_wrapper.py", line 1, in <module>
    from swarms.structs.agent import Agent
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/structs/__init__.py", line 1, in <module>
    from swarms.structs.agent import Agent
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/structs/agent.py", line 15, in <module>
    from swarms.memory.base_vectordb import AbstractVectorDatabase
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/memory/__init__.py", line 7, in <module>
    from swarms.memory.lanchain_chroma import LangchainChromaVectorMemory
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/memory/lanchain_chroma.py", line 10, in <module>
    from swarms.models.openai_models import OpenAIChat
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/models/__init__.py", line 32, in <module>
    from swarms.models.openai_models import (
  File "/Users/athena/Library/Python/3.9/lib/python/site-packages/swarms/models/openai_models.py", line 228, in <module>
    class BaseOpenAI(BaseLLM):
  File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 400, in pydantic.typing.resolve_annotations
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py", line 546, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
athena@Athenas-MacBook-Pro athena % 
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/399">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/399/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/399/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Hi starshipvc,

This appears to be coming from "/Users/athena/Desktop/athena/sam_altman.py".
Would you be able to share a minimal reproducable example?
https://en.wikipedia.org/wiki/Minimal_reproducible_example

Please ask any questions you may have,
Evelyn Mitchell

**Comment by evelynmitchell** [comment]
This is an issue affecting code written by the OP, and had had no activity for a long time.
It can be closed
