### ISSUE TITLE
[BUG] No module named 'swarms_cloud.utils

### ISSUE THREAD

**Issue by peytontolbert** [kyegomez/swarms#600]
**Describe the bug**

**To Reproduce**
1. Update swarms package
2. Run script with 'from swarms import Agent' and run an agent
3. See error:
```

Traceback (most recent call last):
  File "D:\billionpersonas\extract.py", line 4, in <module>
    from swarms import Agent
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\__init__.py", line 10, in <module>
    from swarms.agents import *  # noqa: E402, F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\agents\__init__.py", line 13, in <module>
    from swarms.agents.tool_agent import ToolAgent
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\agents\tool_agent.py", line 3, in <module>
    from swarms.structs.agent import Agent
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\structs\__init__.py", line 1, in <module>
    from swarms.structs.agent import Agent
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\structs\agent.py", line 30, in <module>
    from swarms.prompts.agent_system_prompts import AGENT_SYSTEM_PROMPT_3
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\prompts\__init__.py", line 10, in <module>
    from swarms.prompts.prompt import Prompt
  File "D:\anaconda3\envs\swarms\Lib\site-packages\swarms\prompts\prompt.py", line 13, in <module>
    from swarms_cloud.utils.log_to_swarms_database import log_agent_data
ModuleNotFoundError: No module named 'swarms_cloud.utils.log_to_swarms_database'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

```
**Expected behavior**
Supposed to run the agent

**Additional context**
had to update swarms_cloud: pip install -U swarms-cloud

may want to be include this with swarms install

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/600">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/600/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/600/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@peytontolbert this issue should be fixed now, I have set a range for the `swarms-cloud` repo, lmk if anyone else has it. I will leave this issue for now until it's certain the issue has been terminated
