### ISSUE TITLE
[BUG] `NameError` in `GroupChat` Initialization Due to Missing `GroupChatLog` Class

### ISSUE THREAD

**Issue by ggiallo28** [kyegomez/swarms#629]
**Describe the bug**  
When attempting to initialize a `GroupChat` instance in the `swarms` library, a `NameError` occurs due to an undefined `GroupChatLog` class. This error blocks the successful creation of the `GroupChat` object, as it is referenced within the code but is missing from the definition or imports.

**To Reproduce**  
Steps to reproduce:
1. Import the `GroupChat` class from the `swarms.structs.groupchat` module.
2. Attempt to create a `GroupChat` instance in a Python script.
3. Run the script.
4. Observe the `NameError` related to `GroupChatLog`.

**Expected behavior**  
The `GroupChat` instance should initialize properly, and logging functionality should work if `GroupChatLog` is intended to manage chat logs. If `GroupChatLog` is necessary, it should be properly defined or imported.

**Error Output**  
The following error message is displayed:

```plaintext
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    group_chat = GroupChat(
                 ^^^^^^^^^^
  File "groupchat.py", line 89, in __init__
    self.group_log = GroupChatLog(
                     ^^^^^^^^^^^^
NameError: name 'GroupChatLog' is not defined. Did you mean: 'GroupChat'?
```

**Additional context**  
This issue suggests that `GroupChatLog` may be missing or incorrectly referenced in the code. If it is meant to manage chat logs, an update to the library might be required to define or import `GroupChatLog` properly. As a temporary workaround, defining a basic `GroupChatLog` class can prevent the error, though logging functionality may be limited.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/629">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/629/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/629/pledge.svg">
</picture>
</a>

**Comment by onyedikachi-david** [comment]
Hello @kyegomez, Can i contribute to this?

**Comment by kyegomez** [comment]
Of course

Sincerely, Kye
Kye Gomez
CEO of The Swarm Corporation
2513 Charleston Rd, Mountain View California

*Contact Information*
[Phone:]  [+1 (786)-695-5339]
[Email] ***@***.***
[Book a call][ https://cal.com/swarms ]
[Swarms Github][ https://github.com/kyegomez/swarms ]
[Swarms website][ https://swarms.world ( https://swarms.world/ ) ]
[Swarms Community][ https://discord.com/servers/agora-999382051935506503 ]
