### ISSUE TITLE
OSError: [Errno 22] Invalid argument when saving CSV due to invalid filename characters

### ISSUE THREAD

**Issue by harshalmore31** [kyegomez/swarms#694]
**Issue**
An `OSError: [Errno 22] Invalid argument` is raised when attempting to save the metadata of a `SpreadsheetSwarm` to a CSV file. This occurs because the generated filename contains characters that are not allowed in filenames on Windows, specifically the colon ":" in the timestamp.

**To Reproduce**
1. Run any task using `SpreadsheetSwarm` that generates metadata.
2. The `_save_metadata` function is called automatically at the end of the run which will call `_save_to_csv` to save the metadata to a CSV file.
3. The program will throw `OSError: [Errno 22] Invalid argument` during the file creation in `aiofiles.open`.

**Expected behavior**
The metadata should be saved to a CSV file without errors. The filename should be compatible with all operating systems.

Error :
```log
Traceback (most recent call last):
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\swarms\structs\swarm_router.py", line 409, in _run
    result = self.swarm.run(task, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\swarms\structs\spreadsheet_swarm.py", line 153, in run
    asyncio.run(self._save_metadata())
  File "C:\ProgramData\anaconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\swarms\structs\spreadsheet_swarm.py", line 254, in _save_metadata
    await self._save_to_csv()
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\swarms\structs\spreadsheet_swarm.py", line 268, in _save_to_csv
    async with aiofiles.open(
               ^^^^^^^^^^^^^^
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'spreadsheet_swarm_2024-12-19T23:48:30.649035_run_id_178a7492ef79440a96ed77f71cf9ca3a.csv' 
```

**Comment by patrickbdevaney** [comment]
I changed the file naming scheme in /swarms/swarms/structs/spreadsheet_swarm.py to not use colons and will include it in a forthcoming PR.

**Comment by kyegomez** [comment]
> I changed the file naming scheme in /swarms/swarms/structs/spreadsheet_swarm.py to not use colons and will include it in a forthcoming PR.

thank you so much lmk when it's here!

**Comment by patrickbdevaney** [comment]
> > I changed the file naming scheme in /swarms/swarms/structs/spreadsheet_swarm.py to not use colons and will include it in a forthcoming PR.
> 
> thank you so much lmk when it's here!

Great, I uploaded the PR. 

The change simply modifies the timestamp based naming format for files and should not otherwise conflict with the spreadsheet swarm.
