### ISSUE TITLE
[BUG]  Failed to import transformers.models.fuyu.processing_fuyu

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#95]
Traceback (most recent call last):
  File "/home/v/swarms/fuyu.py", line 1, in <module>
    from swarms.models.fuyu import Fuyu
  File "/home/v/swarms/swarms/models/fuyu.py", line 2, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1336, in __getattr__
    value = getattr(module, name)
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/v/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.fuyu.processing_fuyu because of the following error (look up to see its traceback):
typing.Optional requires a single type. Got <module 'PIL.Image' from '/usr/lib/python3/dist-packages/PIL/Image.py'>.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/95">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/95/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/95/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This doesn't appear to be a complete traceback.

When I run 
```
pip install --update swarms
from transformers import (
    FuyuForCausalLM,
    AutoTokenizer,
    FuyuProcessor,
    FuyuImageProcessor,
)
```
I do not get a traceback.

**Comment by kyegomez** [comment]
@evelynmitchell @vyomakesh09 This issue has been fixed by just specifying from transformers import Fuyu

**Comment by evelynmitchell** [comment]
Thanks!
